### ISSUE TITLE
unable to deploy on heroku

### ISSUE THREAD

**Issue by vivekvardhanadepu** [stripe/example-terminal-backend#43]
This is the error I am getting while deploying the backend to heroku
```
-----> Building on the Heroku-22 stack
-----> Determining which buildpack to use for this app
-----> Ruby app detected
-----> Installing bundler 2.3.10
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Compiling Ruby/Rack
       Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://heroku-buildpack-ruby.s3.us-east-1.amazonaws.com/heroku-22/ruby-2.7.1.tgz -s -o - | tar zxf - ' failed on attempt 1 of 3.
       Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://heroku-buildpack-ruby.s3.us-east-1.amazonaws.com/heroku-22/ruby-2.7.1.tgz -s -o - | tar zxf - ' failed on attempt 2 of 3.
 !
 !     The Ruby version you are trying to install does not exist on this stack.
 !     
 !     You are trying to install ruby-2.7.1 on heroku-22.
 !     
 !     Ruby ruby-2.7.1 is present on the following stacks:
 !     
 !     - heroku-18
 !     - heroku-20
 !     
 !     Heroku recommends you use the latest supported Ruby version listed here:
 !     https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
 !     
 !     For more information on syntax for declaring a Ruby version see:
 !     https://devcenter.heroku.com/articles/ruby-versions
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed

```

**Comment by SwissMediaRocks** [comment]
same issue

**Comment by pcwizarduk** [comment]
same issue

**Comment by SwissMediaRocks** [comment]
This might be the source: https://github.com/stripe/example-terminal-backend/blob/master/Gemfile

**Comment by SwissMediaRocks** [comment]
@KurtWeston Thanks!
Now I got this:
remote:        Fetching gem metadata from https://rubygems.org/...........
remote:        Your bundle is locked to net-http-persistent (3.1.0) from rubygems repository
remote:        https://rubygems.org/ or installed locally, but that version can no longer be
remote:        found in that source. That means the author of net-http-persistent (3.1.0) has
remote:        removed it. You'll need to update your bundle to a version other than
remote:        net-http-persistent (3.1.0) that hasn't been removed in order to install.
remote:        Bundler Output: Fetching gem metadata from https://rubygems.org/...........
remote:        Your bundle is locked to net-http-persistent (3.1.0) from rubygems repository
remote:        https://rubygems.org/ or installed locally, but that version can no longer be
remote:        found in that source. That means the author of net-http-persistent (3.1.0) has
remote:        removed it. You'll need to update your bundle to a version other than
remote:        net-http-persistent (3.1.0) that hasn't been removed in order to install.

**Comment by SwissMediaRocks** [comment]
Issue resolved by following this! https://stackoverflow.com/questions/73979613/is-there-a-way-to-set-which-heroku-stack-20-for-ex-with-the-deploy-button-url/73979977?noredirect=1#comment130642795_73979977
